services:
  safesentinel-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: safesentinel-api
    command: python3 api/server.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sentinel-network

  safesentinel-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safesentinel-bot
    command: python3 bot/telegram_bot.py
    depends_on:
      - safesentinel-api
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sentinel-network

networks:
  sentinel-network:
    driver: bridge
